rule multiqc:
    input:
        expand(
            "results/fastp/{sample}_fastp.json",
            sample=sample_data.index.tolist(),
        ),
        expand(
            "results/fastqc/{sample}_R1.html",
            sample=sample_data.index.tolist(),
        ),
        expand(
            "results/fastqc/{sample}_R2.html",
            sample=sample_data.index.tolist(),
        ),
        expand(
            "results/sortmerna/{sample}_sortmerna_stats.log",
            sample=sample_data.index.tolist(),
        ),
        "results/busco/short_summary.txt",
        "results/seqkit_transcripts/Transcript_stats_mqc.txt",
        "results/blobtools/Blobtools_summary_mqc.png",
        "results/salmon/quant.sf",
        "results/salmon/lib_format_counts.json",
        config="config/config_multiqc.yaml",
    output:
        "results/multiqc.html",
        directory("results/multiqc_data"),
    log:
        "logs/multiqc.log",
    params:
        extra="--verbose",  # Optional: extra parameters for multiqc.
    wrapper:
        "v7.5.0/bio/multiqc"
